name: tution_pal
description: "A personal assistant for SL students"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI and Utilities
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  path_provider: ^2.1.3

  # Local Storage (Hive)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Firebase
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4



  # Other Services
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  
  # Notifications
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  
  # Timer and DateTime
  intl: ^0.19.0
  
  # Additional UI
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true