name: tution_pal
description: "A personal assistant for SL students"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0' # I adjusted this slightly for broader compatibility, you can keep yours if it works

dependencies:
  flutter:
    sdk: flutter

  # UI and Utilities
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  path_provider: ^2.1.3 # Your version was a bit old, updated

  # Local Storage (Hive)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Firebase
  firebase_core: ^2.25.4 # Updated to recent versions
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4

  # Other Services
  connectivity_plus: ^5.0.2 # Updated to recent versions
  shared_preferences: ^2.2.2
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1 # Updated to recent versions

  # 👉 මෙන්න අලුතෙන් add වෙන්න ඕන lines දෙක!
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true