// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnPkNfTcuzHEygh2YtfVgL5SscyI_7k4E',
    appId: '1:973839467495:web:3b693aad85c98056cc7342',
    messagingSenderId: '973839467495',
    projectId: 'mindle-56696',
    authDomain: 'mindle-56696.firebaseapp.com',
    storageBucket: 'mindle-56696.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnPkNfTcuzHEygh2YtfVgL5SscyI_7k4E',
    appId: '1:973839467495:android:3b693aad85c98056cc7342',
    messagingSenderId: '973839467495',
    projectId: 'mindle-56696',
    storageBucket: 'mindle-56696.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnPkNfTcuzHEygh2YtfVgL5SscyI_7k4E',
    appId: '1:973839467495:ios:3b693aad85c98056cc7342',
    messagingSenderId: '973839467495',
    projectId: 'mindle-56696',
    storageBucket: 'mindle-56696.firebasestorage.app',
    iosClientId: '973839467495-abcdef123456.apps.googleusercontent.com',
    iosBundleId: 'lk.mindle.tutionPal.tutionPal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnPkNfTcuzHEygh2YtfVgL5SscyI_7k4E',
    appId: '1:973839467495:macos:3b693aad85c98056cc7342',
    messagingSenderId: '973839467495',
    projectId: 'mindle-56696',
    storageBucket: 'mindle-56696.firebasestorage.app',
    iosClientId: '973839467495-abcdef123456.apps.googleusercontent.com',
    iosBundleId: 'lk.mindle.tutionPal.tutionPal',
  );
}